export const projects: ProjectData[] = [
  {
    id: 1,
    title: "Blog Site",
    image: "",
    desc: "It is a simple blog clone with search functionality and an admin panel for managing the staff and blog posts.",
    stack: "NextJs, TypeScript, Tailwind, MongoDB",
    source: "https://github.com/ajfuturistics/blog-site",
    live: "",
  },
  {
    id: 2,
    title: "Ai Prompt Sharing site",
    image: "",
    desc: "A NextJS full-stack project with CRUD operations. Users can log in to this, share AI prompts, and view other prompts.",
    stack: "NextJs, TypeScript, Tailwind, MongoDB",
    source: "https://github.com/ajfuturistics/nextjs-project-with-typescript",
    live: "",
  },
  {
    id: 3,
    title: "Social Media Clone with Chat",
    image: "",
    desc: "a whole project built on the MERN stack. Users can log in, exchange content, and have friend chats on this. It's a Twitter clone.",
    stack: "ReactJs, Tailwind, Redux, NodeJs, MongoDB, Socket.Io",
    source: "https://github.com/ajfuturistics/social-media-clone-with-chat",
    live: "",
  },
  {
    id: 4,
    title: "Recipe App Using React",
    image: "",
    desc: "This website displays recipes and related data, such as calorie counts, ingredient lists, cuisine types, etc.",
    stack: "ReactJs",
    source: "https://github.com/ajfuturistics/Recipe-App-Using-React",
    live: "",
  },
  {
    id: 5,
    title: "React Native Shopping App",
    image: "",
    desc: "Customers can purchase items with this smartphone app. Admins can handle orders and products via the admin interface.",
    stack: "React Native, Expo, Firebase",
    source: "https://github.com/ajfuturistics/React-native-expo-shopping-app",
    live: "",
  },
  {
    id: 6,
    title: "HealthCare App using Python",
    image: "",
    desc: "Thi App makes it easier for patients to set up appointments and consultations and makes it simple for doctors to view their schedules.",
    stack: "Python, QT5, SQLite",
    source: "https://github.com/ajfuturistics/HealthCare-App-using-Python",
    live: "",
  },
];
