export const projects: ProjectData[] = [
  {
    id: 1,
    title: "Blog Site",
    image: "",
    desc: "In this site users can use this to look up blog entries and filter their results by title or category. In the admin interface, which is used to manage blog entries, administrators can also add staff members.",
    stack: "NextJs, TypeScript, Tailwind, MongoDB",
    source: "https://github.com/ajfuturistics/blog-site",
    live: "",
  },
  {
    id: 2,
    title: "Ai Prompt Sharing site",
    image: "",
    desc: "Fullstack project made in nextjs with CRUD operations. In this users can login and share AI prompts and check others prompts",
    stack: "NextJs, TypeScript, Tailwind, MongoDB",
    source: "https://github.com/ajfuturistics/nextjs-project-with-typescript",
    live: "",
  },
  {
    id: 3,
    title: "Social Media Clone with Chat",
    image: "",
    desc: "Fullstack project made in MERN stack. In this users can login and share posts and chat with friends. It is twitter clone",
    stack: "ReactJs, Tailwind, Redux, NodeJs, MongoDB, Socket.Io",
    source: "https://github.com/ajfuturistics/social-media-clone-with-chat",
    live: "",
  },
  {
    id: 4,
    title: "Recipe App Using React",
    image: "",
    desc: "This app designed to get recipes you wanted and give information about it like calories, ingredients, cuisine type etc. I used Edamam Recipe Api to get recipes.",
    stack: "ReactJs",
    source: "https://github.com/ajfuturistics/Recipe-App-Using-React",
    live: "",
  },
  {
    id: 5,
    title: "React Native Expo Shopping App",
    image: "",
    desc: "This is e-commerse mobile app in this users can shop for products. In admin panel admin can add products and manage orders",
    stack: "React Native, Expo, Firebase",
    source: "https://github.com/ajfuturistics/React-native-expo-shopping-app",
    live: "",
  },
  {
    id: 6,
    title: "HealthCare App using Python",
    image: "",
    desc: "Health Care App is developed specifically to ease appointment and consultation process for patients and for doctors to check appointments easily. ",
    stack: "Python, QT5, SQLite",
    source: "https://github.com/ajfuturistics/HealthCare-App-using-Python",
    live: "",
  },
];
