export const projects: ProjectData[] = [
  {
    id: 1,
    title: "Alosrah Hospital",
    image: "",
    desc: "I made the website for the ENR Client. It contains two languages (En and Ar) that are available, allows users to plan appointments, and hospitals to manage patients and their treatment histories.",
    stack: "React, Node.Js, MongoDB, Express.Js, Tailwind CSS",
    source: "",
    live: "https://osra-hospital.vercel.app/",
  },
  {
    id: 2,
    title: "Gurri Admin Dashboard",
    image: "",
    desc: "It is an admin dashboard used to control the Gurri eCommerce website's goods and services. Admins may view all information, including the current total of payments collected and the number of active users.",
    stack: "Node.Js, Firebase",
    source: "",
    live: "",
  },
  {
    id: 3,
    title: "Gurri Shopping Website",
    image: "",
    desc: "It is an online store that provides a variety of services, including plasterer service, electrician service, painter service, plumber service, handyman service, and builder service. Additionally, it incorporates Stripe payments.",
    stack: "React, Express, Node.Js, Firebase",
    source: "",
    live: "",
  },
  {
    id: 4,
    title: "Genesis Transformation & Innovation Pvt Ltd",
    image: "",
    desc: "I created the website using reactjs, nodejs, and tailwindcss for the ENR Client, and I later revamped it using nextjs.",
    stack: "NextJs, Tailwind",
    source: "",
    live: "https://gct-new.vercel.app/",
  },
  {
    id: 5,
    title: "aHope Buyer & Seller",
    image: "",
    desc: "These are two websites where buyers can place bids on things that sellers have listed and sell them for the price they desire. Once the seller has accepted that bid, they can talk and monitor the situation.",
    stack: "React, Material UI, Tailwind CSS",
    source: "",
    live: "",
  },
  {
    id: 6,
    title: "Driver Tracker",
    image: "",
    desc: "Drivers begin their shift by entering information on this website, such as how many packages they took, and at the end of their shift, they enter information regarding packages that were delivered and those that were not, along with the reasons for each. and the manger can export it to an Excel document for review.",
    stack: "React, Tailwind CSS",
    source: "",
    live: "",
  },
  {
    id: 7,
    title: "ENR LMS",
    image: "",
    desc: "On this platform, which is similar to Udemy, instructors are able to create courses, and users are able to join in and consume content from the courses of their choice.",
    stack: "React, Material UI, Tailwind CSS",
    source: "",
    live: "",
  },
  {
    id: 8,
    title: "Blog Site",
    image: "",
    desc: "It is a simple blog clone with search functionality and an admin panel for managing the staff and blog posts.",
    stack: "NextJs, TypeScript, Tailwind, MongoDB",
    source: "https://github.com/ajfuturistics/blog-site",
    live: "",
  },
  {
    id: 9,
    title: "Social Media Clone with Chat",
    image: "",
    desc: "It is a chat-based Twitter clone. built entirely on the MERN stack. On here, users can log in, add and manage posts, and talk with friends.",
    stack: "ReactJs, Tailwind, Redux, NodeJs, MongoDB, Socket.Io",
    source: "https://github.com/ajfuturistics/social-media-clone-with-chat",
    live: "",
  },
  {
    id: 10,
    title: "Basic Event Scheduling",
    image: "",
    desc: "simple website for arranging events. Users can schedule events at any time and date they like, as well as view, update, and remove them using an interface that was inspired by Google Calendar.",
    stack: "ReactJs",
    source: "https://github.com/ajfuturistics/Recipe-App-Using-React",
    live: "",
  },
  {
    id: 11,
    title: "React Native Shopping App",
    image: "",
    desc: "Customers can purchase items with this smartphone app. Admins can handle orders and products via the admin interface.",
    stack: "React Native, Expo, Firebase",
    source: "https://github.com/ajfuturistics/React-native-expo-shopping-app",
    live: "",
  },
  {
    id: 12,
    title: "HealthCare App using Python",
    image: "",
    desc: "This is my college project. This software makes it simple for doctors to access their schedules and for patients to arrange appointments and consultations.",
    stack: "Python, QT5, SQLite",
    source: "https://github.com/ajfuturistics/HealthCare-App-using-Python",
    live: "",
  },
];
